"""
PCLL Safety, Ethical, and Legal Guardrails
============================================

This module defines comprehensive guardrails to ensure PCLL:
1. Clearly differentiates from mental health tools
2. Protects user autonomy
3. Uses patent-safe language
4. Mitigates legal and ethical risks

CRITICAL: All user-facing text MUST pass through these guardrails.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Set, Tuple, Optional
from enum import Enum
import re


# =============================================================================
# SECTION 1: EXPLICIT DISCLAIMERS
# =============================================================================

class DisclaimerType(Enum):
    """Categories of disclaimers required at different touchpoints."""
    FIRST_USE = "first_use"           # Shown on first app launch
    DAILY_REMINDER = "daily_reminder"  # Periodic reinforcement
    INSIGHT_FOOTER = "insight_footer"  # Appended to insights
    EXPORT_HEADER = "export_header"    # Included in data exports
    HELP_RESOURCES = "help_resources"  # When user may need support


@dataclass
class Disclaimer:
    """A single disclaimer with metadata."""
    type: DisclaimerType
    title: str
    text: str
    must_acknowledge: bool = False  # Requires user confirmation
    show_frequency: str = "once"    # once, daily, always


# Primary disclaimers that MUST be shown
DISCLAIMERS: Dict[DisclaimerType, Disclaimer] = {
    
    DisclaimerType.FIRST_USE: Disclaimer(
        type=DisclaimerType.FIRST_USE,
        title="Important Information About PCLL",
        text="""
PERSONAL COGNITIVE LOAD LEDGER (PCLL) - DISCLAIMER

WHAT THIS IS:
PCLL is a personal productivity tracking tool that uses a banking metaphor 
to help you observe patterns in your daily cognitive workload. It tracks 
self-reported data about tasks, decisions, and recovery activities.

WHAT THIS IS NOT:
• NOT a medical device or health monitoring tool
• NOT a mental health assessment or diagnostic tool
• NOT a substitute for professional medical advice
• NOT a treatment for any condition
• NOT validated for clinical use

IMPORTANT LIMITATIONS:
• All calculations are estimates based on self-reported data
• The "Cognitive Units" (CU) are an arbitrary metaphorical unit
• Results reflect only what you report, not objective measurements
• This tool cannot detect, diagnose, or treat any health condition

BY USING THIS TOOL, YOU ACKNOWLEDGE:
1. You understand this is a productivity observation tool only
2. You will not use this to make health-related decisions
3. You will seek professional help for any health concerns
4. The developers are not responsible for decisions made based on this data

If you are experiencing distress, please contact a healthcare professional
or crisis helpline in your area.
        """.strip(),
        must_acknowledge=True,
        show_frequency="once"
    ),
    
    DisclaimerType.DAILY_REMINDER: Disclaimer(
        type=DisclaimerType.DAILY_REMINDER,
        title="Reminder",
        text="""
PCLL tracks self-reported workload patterns. It is not a health tool.
All values are estimates using an arbitrary unit system.
        """.strip(),
        must_acknowledge=False,
        show_frequency="weekly"
    ),
    
    DisclaimerType.INSIGHT_FOOTER: Disclaimer(
        type=DisclaimerType.INSIGHT_FOOTER,
        title="",
        text="""
This observation is based on self-reported data and uses estimated calculations.
It is not a health assessment.
        """.strip(),
        must_acknowledge=False,
        show_frequency="always"
    ),
    
    DisclaimerType.EXPORT_HEADER: Disclaimer(
        type=DisclaimerType.EXPORT_HEADER,
        title="Data Export Notice",
        text="""
PCLL DATA EXPORT

This data represents self-reported cognitive workload observations.
- "Cognitive Units" (CU) are arbitrary metaphorical values, not clinical measurements
- All calculations are estimates based on rule-based formulas
- This data is NOT suitable for medical, diagnostic, or clinical purposes
- This data should NOT be shared with healthcare providers as health information

Generated by Personal Cognitive Load Ledger (PCLL) - A productivity observation tool
        """.strip(),
        must_acknowledge=False,
        show_frequency="always"
    ),
    
    DisclaimerType.HELP_RESOURCES: Disclaimer(
        type=DisclaimerType.HELP_RESOURCES,
        title="Need Support?",
        text="""
PCLL is a productivity tool and cannot provide health support.

If you're experiencing:
• Persistent stress or overwhelm
• Sleep difficulties
• Emotional distress
• Thoughts of self-harm

Please reach out to:
• Your primary care physician
• A mental health professional
• National crisis helplines in your country
• Emergency services if in immediate danger

This tool is not equipped to provide crisis support or health advice.
        """.strip(),
        must_acknowledge=False,
        show_frequency="always"
    )
}


# =============================================================================
# SECTION 2: LANGUAGE GUARDRAILS
# =============================================================================

@dataclass
class LanguageGuardrails:
    """
    Comprehensive language restrictions to ensure PCLL stays in its lane.
    
    Three categories:
    1. BLACKLIST: Terms that must NEVER appear
    2. CAUTION: Terms that need careful context
    3. PREFERRED: Terms to use instead of problematic ones
    """
    
    # -------------------------------------------------------------------------
    # CLINICAL/MEDICAL TERMS - NEVER USE
    # -------------------------------------------------------------------------
    # These terms could imply medical capability or diagnosis
    CLINICAL_BLACKLIST: Set[str] = field(default_factory=lambda: {
        # Mental health conditions
        "depression", "depressed", "anxiety", "anxious",
        "burnout", "burned out", "burn-out",
        "ptsd", "trauma", "traumatic",
        "bipolar", "adhd", "add", "ocd",
        "disorder", "syndrome", "condition",
        "mental health", "mental illness", "psychiatric",
        
        # Medical terms
        "diagnosis", "diagnose", "diagnosed",
        "symptom", "symptoms", "symptomatic",
        "treatment", "treat", "treating",
        "therapy", "therapeutic", "therapist",
        "clinical", "clinician", "clinically",
        "medical", "medicine", "medication",
        "prescription", "prescribe",
        "pathology", "pathological",
        "chronic", "acute",
        
        # Healthcare roles
        "doctor", "physician", "psychiatrist", "psychologist",
        "counselor", "therapist", "healthcare provider",
        
        # Severity implications
        "severe", "serious", "critical", "dangerous",
        "emergency", "crisis", "urgent",
    })
    
    # -------------------------------------------------------------------------
    # WELLNESS/SELF-HELP TERMS - NEVER USE
    # -------------------------------------------------------------------------
    # These could imply wellness coaching or life advice
    WELLNESS_BLACKLIST: Set[str] = field(default_factory=lambda: {
        # Self-help language
        "self-care", "self care", "wellness",
        "healing", "heal", "healed",
        "mindfulness", "mindful", "meditation",
        "balance your life", "work-life balance",
        "holistic", "wholeness",
        
        # Coaching language
        "unlock your potential", "reach your goals",
        "transform", "transformation",
        "empower", "empowerment", "empowering",
        "journey", "path to", "road to",
        "breakthrough", "break through",
        
        # Prescriptive wellness
        "you need to relax", "take care of yourself",
        "be kind to yourself", "practice gratitude",
    })
    
    # -------------------------------------------------------------------------
    # EMOTIONAL/FEELING TERMS - NEVER USE
    # -------------------------------------------------------------------------
    # PCLL should not interpret or label emotions
    EMOTIONAL_BLACKLIST: Set[str] = field(default_factory=lambda: {
        # Emotional states
        "stressed", "stress", "stressful",
        "overwhelmed", "overwhelming",
        "exhausted", "exhaustion",
        "fatigued", "fatigue",  # Exception: "decision fatigue" as technical term
        "frustrated", "frustration",
        "worried", "worry", "worrying",
        "sad", "sadness", "unhappy",
        "angry", "anger", "irritable",
        "hopeless", "helpless",
        
        # Emotional interpretations
        "you feel", "you're feeling",
        "you seem", "you appear",
        "you must be feeling",
        "emotionally", "emotional state",
    })
    
    # -------------------------------------------------------------------------
    # MOTIVATIONAL LANGUAGE - NEVER USE
    # -------------------------------------------------------------------------
    # Avoids patronizing or cheerleading tone
    MOTIVATIONAL_BLACKLIST: Set[str] = field(default_factory=lambda: {
        # Praise
        "great job", "well done", "good job",
        "amazing", "fantastic", "wonderful", "excellent",
        "proud of you", "congratulations",
        "way to go", "keep it up", "keep going",
        
        # Encouragement
        "you can do it", "you've got this",
        "believe in yourself", "stay strong",
        "don't give up", "hang in there",
        "tomorrow is a new day", "things will get better",
        "stay positive", "look on the bright side",
        
        # Diminishing
        "no big deal", "don't worry",
        "it's okay", "it's fine",
        "just relax", "calm down",
    })
    
    # -------------------------------------------------------------------------
    # PRESCRIPTIVE PATTERNS - NEVER USE
    # -------------------------------------------------------------------------
    # Regex patterns for prescriptive/advisory language
    PRESCRIPTIVE_PATTERNS: List[str] = field(default_factory=lambda: [
        r"\byou should\b",
        r"\byou must\b",
        r"\byou need to\b",
        r"\byou have to\b",
        r"\btry to\b",
        r"\bmake sure to\b",
        r"\bdon't forget to\b",
        r"\bremember to\b",
        r"\bi recommend\b",
        r"\bi suggest\b",
        r"\bi advise\b",
        r"\bconsider\b",
        r"\bperhaps you could\b",
        r"\bmaybe you should\b",
        r"\bwhy don't you\b",
        r"\bhave you tried\b",
        r"\bit would be good to\b",
        r"\bit's important to\b",
    ])
    
    # -------------------------------------------------------------------------
    # CAUTION TERMS - USE WITH CARE
    # -------------------------------------------------------------------------
    # These are acceptable in specific technical contexts only
    CAUTION_TERMS: Dict[str, str] = field(default_factory=lambda: {
        "fatigue": "Only use as 'decision fatigue' - a cognitive science term",
        "load": "Only use as 'cognitive load' - a technical productivity term",
        "capacity": "Acceptable for describing work capacity metaphorically",
        "recovery": "Acceptable for describing breaks/rest in productivity context",
        "deficit": "Acceptable as accounting metaphor, not health deficit",
        "drain": "Acceptable as metaphor for cognitive resource depletion",
        "restore": "Acceptable for describing capacity restoration",
    })
    
    # -------------------------------------------------------------------------
    # PREFERRED ALTERNATIVES
    # -------------------------------------------------------------------------
    # What to say INSTEAD of problematic terms
    PREFERRED_ALTERNATIVES: Dict[str, str] = field(default_factory=lambda: {
        # Instead of emotional terms
        "stressed": "high withdrawal day",
        "overwhelmed": "withdrawals exceeded capacity",
        "exhausted": "low closing balance",
        "burned out": "extended deficit period",
        
        # Instead of prescriptive
        "you should rest": "recovery deposits increase balance",
        "take a break": "lower withdrawal activities",
        "you need to slow down": "current withdrawal rate exceeds deposits",
        
        # Instead of clinical
        "symptoms": "patterns in the data",
        "diagnosis": "observation",
        "treatment": "adjustment",
        "healthy": "positive balance",
        "unhealthy": "deficit balance",
        
        # Instead of motivational
        "great job": "balance increased",
        "keep it up": "pattern continues",
        "you're doing well": "positive trend observed",
    })


# =============================================================================
# SECTION 3: FEATURE LIMITATIONS
# =============================================================================

@dataclass
class FeatureLimitation:
    """A specific limitation on what PCLL can/cannot do."""
    category: str
    limitation: str
    rationale: str
    enforcement: str  # How this is enforced technically


FEATURE_LIMITATIONS: List[FeatureLimitation] = [
    
    # Data Collection Limits
    FeatureLimitation(
        category="Data Collection",
        limitation="No biometric data collection",
        rationale="Biometrics could imply health monitoring capability",
        enforcement="No APIs for heart rate, sleep tracking, etc. Only manual input."
    ),
    FeatureLimitation(
        category="Data Collection",
        limitation="No passive/automatic data collection",
        rationale="User must actively choose what to report; protects autonomy",
        enforcement="All data entry requires explicit user action."
    ),
    FeatureLimitation(
        category="Data Collection",
        limitation="No location or calendar integration",
        rationale="Could enable surveillance-like features; privacy risk",
        enforcement="No location permissions requested; no calendar API access."
    ),
    
    # Analysis Limits
    FeatureLimitation(
        category="Analysis",
        limitation="No predictive health claims",
        rationale="Cannot predict burnout, illness, or health outcomes",
        enforcement="Insights limited to observational statements about past data."
    ),
    FeatureLimitation(
        category="Analysis",
        limitation="No comparisons to population norms",
        rationale="Could imply clinical assessment or 'normal' ranges",
        enforcement="All metrics shown only relative to user's own history."
    ),
    FeatureLimitation(
        category="Analysis",
        limitation="No severity scoring or risk levels",
        rationale="Could be interpreted as health risk assessment",
        enforcement="No 'danger zones', 'risk scores', or color-coded health warnings."
    ),
    FeatureLimitation(
        category="Analysis",
        limitation="Maximum 1 insight per day",
        rationale="Prevents advice overload and over-interpretation",
        enforcement="InsightEngine returns at most one insight per generate_insight() call."
    ),
    
    # Output Limits
    FeatureLimitation(
        category="Output",
        limitation="No personalized recommendations",
        rationale="PCLL observes patterns, does not advise actions",
        enforcement="Language guardrails block all prescriptive patterns."
    ),
    FeatureLimitation(
        category="Output",
        limitation="No notifications or alerts",
        rationale="Push notifications could create anxiety; user pulls data when ready",
        enforcement="No push notification system; all interaction is user-initiated."
    ),
    FeatureLimitation(
        category="Output",
        limitation="No gamification elements",
        rationale="Streaks/rewards could encourage unhealthy usage patterns",
        enforcement="No badges, achievements, leaderboards, or streak counters."
    ),
    
    # Integration Limits
    FeatureLimitation(
        category="Integration",
        limitation="No sharing to social media",
        rationale="Prevents social comparison and protects privacy",
        enforcement="No social sharing APIs or features."
    ),
    FeatureLimitation(
        category="Integration",
        limitation="No employer/third-party data sharing",
        rationale="Protects user autonomy; data is personal only",
        enforcement="No export formats designed for HR systems; explicit warnings on any export."
    ),
    FeatureLimitation(
        category="Integration",
        limitation="No health app ecosystem integration",
        rationale="Could imply health tool status; regulatory risk",
        enforcement="No Apple Health, Google Fit, or health platform APIs."
    ),
]


# =============================================================================
# SECTION 4: RISK MITIGATION STRATEGIES
# =============================================================================

@dataclass
class RiskScenario:
    """A potential risk scenario and how to mitigate it."""
    risk_id: str
    description: str
    likelihood: str  # Low, Medium, High
    impact: str      # Low, Medium, High, Critical
    mitigation_strategies: List[str]
    detection_method: str
    response_protocol: str


RISK_SCENARIOS: List[RiskScenario] = [
    
    RiskScenario(
        risk_id="RISK-001",
        description="User interprets PCLL data as health diagnosis",
        likelihood="Medium",
        impact="High",
        mitigation_strategies=[
            "Mandatory disclaimer acknowledgment on first use",
            "Disclaimer footer on all insights",
            "Clear 'What This Is Not' section in onboarding",
            "Avoid all clinical terminology in outputs",
            "Use obviously metaphorical language (banking terms)",
        ],
        detection_method="User feedback monitoring; support ticket analysis",
        response_protocol="Clarify tool purpose; direct to healthcare resources"
    ),
    
    RiskScenario(
        risk_id="RISK-002",
        description="User in crisis relies on PCLL instead of seeking help",
        likelihood="Low",
        impact="Critical",
        mitigation_strategies=[
            "Prominent 'Need Support?' link to crisis resources",
            "No crisis detection or intervention features (avoid false capability)",
            "Clear statement that tool cannot provide support",
            "No 'severe' or 'dangerous' language that could minimize real crises",
        ],
        detection_method="Cannot detect; mitigation is preventive messaging",
        response_protocol="Ensure help resources are always visible and accessible"
    ),
    
    RiskScenario(
        risk_id="RISK-003",
        description="Employer uses PCLL data to monitor/evaluate employees",
        likelihood="Medium",
        impact="High",
        mitigation_strategies=[
            "No enterprise/team features",
            "Export includes strong disclaimer against workplace use",
            "Terms of service prohibit employer-mandated use",
            "Data stored locally only (no cloud sync by default)",
            "No aggregation or benchmarking features",
        ],
        detection_method="Terms of service violation reports",
        response_protocol="Terminate access for violating organizations"
    ),
    
    RiskScenario(
        risk_id="RISK-004",
        description="User develops unhealthy relationship with tracking",
        likelihood="Medium",
        impact="Medium",
        mitigation_strategies=[
            "No gamification (streaks, rewards, achievements)",
            "No notifications or prompts to log",
            "No 'perfect day' or optimization targets",
            "Limit to 1 insight per day (reduce obsessive checking)",
            "No historical comparison that encourages competition with self",
        ],
        detection_method="Usage pattern analysis (optional, privacy-preserving)",
        response_protocol="Surface 'Taking a break from tracking is okay' message"
    ),
    
    RiskScenario(
        risk_id="RISK-005",
        description="Regulatory body classifies PCLL as medical device",
        likelihood="Low",
        impact="Critical",
        mitigation_strategies=[
            "No health claims in any marketing or in-app text",
            "No biometric integration",
            "Clear 'productivity tool' positioning throughout",
            "Legal review of all user-facing text",
            "Avoid terms like 'monitor', 'track health', 'wellness'",
            "Documentation of intended use as productivity tool only",
        ],
        detection_method="Regulatory inquiry or legal notice",
        response_protocol="Legal counsel engagement; immediate compliance review"
    ),
    
    RiskScenario(
        risk_id="RISK-006",
        description="Patent infringement claim from existing IP holders",
        likelihood="Medium",
        impact="High",
        mitigation_strategies=[
            "Use generic accounting/ledger terminology (public domain)",
            "Avoid trademarked wellness terms",
            "Document prior art for core concepts",
            "Use 'Cognitive Units' as clearly arbitrary/metaphorical",
            "Open-source core algorithms for defensive publication",
        ],
        detection_method="Patent search; legal monitoring",
        response_protocol="Legal review; modify terminology if needed"
    ),
    
    RiskScenario(
        risk_id="RISK-007",
        description="Data breach exposes sensitive user patterns",
        likelihood="Low",
        impact="High",
        mitigation_strategies=[
            "Local-first storage (SQLite on device)",
            "No cloud sync by default",
            "Optional encryption for database",
            "No PII required (user_id can be anonymous)",
            "Clear data deletion capability",
        ],
        detection_method="Security monitoring; penetration testing",
        response_protocol="Incident response plan; user notification within 72 hours"
    ),
]


# =============================================================================
# SECTION 5: PATENT-SAFE LANGUAGE
# =============================================================================

@dataclass
class PatentSafeTerminology:
    """
    Terminology choices designed to avoid patent conflicts.
    Uses generic, public-domain concepts from accounting and cognitive science.
    """
    
    # Core metaphor: Banking/Accounting (public domain since ancient Babylon)
    SAFE_TERMS: Dict[str, str] = field(default_factory=lambda: {
        # Primary concepts
        "cognitive_units": "Arbitrary metaphorical unit (like frequent flyer miles)",
        "ledger": "Standard accounting term (public domain)",
        "balance": "Standard accounting term (public domain)",
        "withdrawal": "Standard accounting term (public domain)",
        "deposit": "Standard accounting term (public domain)",
        "deficit": "Standard accounting term (public domain)",
        "carryover": "Standard accounting term (public domain)",
        
        # Technical concepts (established cognitive science)
        "cognitive_load": "Established term from Sweller (1988) - widely used",
        "context_switching": "Established term in psychology and computing",
        "decision_fatigue": "Established term from Baumeister research",
        "working_memory": "Established term from Baddeley (1974)",
        
        # Metaphorical descriptions
        "capacity": "Generic term, not proprietary",
        "recovery": "Generic term for rest/restoration",
        "drain": "Generic metaphor for resource depletion",
    })
    
    # Terms to AVOID due to potential IP issues
    POTENTIALLY_PROBLEMATIC: Dict[str, str] = field(default_factory=lambda: {
        "energy score": "May conflict with wellness app patents",
        "stress level": "May conflict with health monitoring patents",
        "burnout index": "May conflict with HR tech patents",
        "wellness score": "May conflict with health platform patents",
        "mental battery": "May conflict with mental health app patents",
        "brain budget": "Could be trademarked",
        "mind meter": "Could be trademarked",
        "cognitive fitness": "May conflict with brain training patents",
    })
    
    # Prior art documentation for defensive purposes
    PRIOR_ART_REFERENCES: List[str] = field(default_factory=lambda: [
        "Cognitive Load Theory - Sweller, 1988",
        "Working Memory Model - Baddeley & Hitch, 1974",
        "Decision Fatigue Research - Baumeister et al., 2008",
        "Context Switching Costs - Monsell, 2003",
        "Zeigarnik Effect - Zeigarnik, 1927",
        "Double-Entry Bookkeeping - Pacioli, 1494",
        "Personal Finance Tracking - Generic category, numerous prior art",
    ])


# =============================================================================
# SECTION 6: VALIDATION ENGINE
# =============================================================================

class SafetyValidator:
    """
    Runtime validator to ensure all outputs comply with guardrails.
    Should be called before any text is shown to users.
    """
    
    def __init__(self):
        self.guardrails = LanguageGuardrails()
        self._compile_patterns()
    
    def _compile_patterns(self):
        """Pre-compile regex patterns for efficiency."""
        self._prescriptive_patterns = [
            re.compile(pattern, re.IGNORECASE) 
            for pattern in self.guardrails.PRESCRIPTIVE_PATTERNS
        ]
    
    def validate_text(self, text: str) -> Tuple[bool, List[str]]:
        """
        Validate text against all guardrails.
        
        Returns:
            (is_valid, list_of_violations)
        """
        violations = []
        text_lower = text.lower()
        
        # Check clinical blacklist
        for term in self.guardrails.CLINICAL_BLACKLIST:
            if term in text_lower:
                violations.append(f"Clinical term detected: '{term}'")
        
        # Check wellness blacklist
        for term in self.guardrails.WELLNESS_BLACKLIST:
            if term in text_lower:
                violations.append(f"Wellness term detected: '{term}'")
        
        # Check emotional blacklist (with exceptions)
        for term in self.guardrails.EMOTIONAL_BLACKLIST:
            if term in text_lower:
                # Allow "decision fatigue" as technical term
                if term == "fatigue" and "decision fatigue" in text_lower:
                    continue
                violations.append(f"Emotional term detected: '{term}'")
        
        # Check motivational blacklist
        for term in self.guardrails.MOTIVATIONAL_BLACKLIST:
            if term in text_lower:
                violations.append(f"Motivational term detected: '{term}'")
        
        # Check prescriptive patterns
        for pattern in self._prescriptive_patterns:
            if pattern.search(text_lower):
                violations.append(f"Prescriptive pattern detected: '{pattern.pattern}'")
        
        return (len(violations) == 0, violations)
    
    def suggest_alternative(self, problematic_term: str) -> Optional[str]:
        """Suggest a safe alternative for a problematic term."""
        return self.guardrails.PREFERRED_ALTERNATIVES.get(
            problematic_term.lower()
        )
    
    def get_safe_message(self, text: str) -> str:
        """
        Attempt to make text safe by replacing known problematic terms.
        WARNING: This is a fallback; text should be written safely from the start.
        """
        result = text
        for problematic, safe in self.guardrails.PREFERRED_ALTERNATIVES.items():
            # Case-insensitive replacement
            pattern = re.compile(re.escape(problematic), re.IGNORECASE)
            result = pattern.sub(safe, result)
        return result


# =============================================================================
# SECTION 7: COMPLIANCE CHECKLIST
# =============================================================================

def generate_compliance_checklist() -> str:
    """
    Generate a compliance checklist for developers/reviewers.
    """
    checklist = """
PCLL SAFETY COMPLIANCE CHECKLIST
=================================

Before releasing any user-facing text or feature, verify:

□ DISCLAIMERS
  □ First-use disclaimer is shown and requires acknowledgment
  □ Insight footer disclaimer is appended to all insights
  □ Export header disclaimer is included in all data exports
  □ Help resources link is accessible from main interface

□ LANGUAGE REVIEW
  □ No clinical/medical terms (see CLINICAL_BLACKLIST)
  □ No wellness/self-help terms (see WELLNESS_BLACKLIST)
  □ No emotional interpretations (see EMOTIONAL_BLACKLIST)
  □ No motivational language (see MOTIVATIONAL_BLACKLIST)
  □ No prescriptive patterns ("you should", "try to", etc.)
  □ All text validated through SafetyValidator

□ FEATURE CONSTRAINTS
  □ No biometric data collection
  □ No passive/automatic tracking
  □ No predictive health claims
  □ No severity scores or risk levels
  □ Maximum 1 insight per day enforced
  □ No push notifications
  □ No gamification elements
  □ No social sharing features
  □ No health app integrations

□ DATA PROTECTION
  □ All data stored locally by default
  □ No cloud sync without explicit consent
  □ Clear data deletion option available
  □ Export includes appropriate disclaimers
  □ No employer/third-party sharing features

□ LEGAL REVIEW
  □ No health claims in marketing materials
  □ Patent-safe terminology used throughout
  □ Terms of service prohibit workplace surveillance use
  □ Privacy policy accurately reflects data practices
  □ Regulatory classification documented (productivity tool, not medical device)

□ RISK MITIGATION
  □ Crisis resources accessible (not crisis intervention features)
  □ Clear "what this is not" messaging
  □ No language that could minimize real health concerns
  □ Incident response plan documented

Reviewer: _______________
Date: _______________
Version: _______________
"""
    return checklist


# =============================================================================
# SECTION 8: DEMONSTRATION
# =============================================================================

def demonstrate_guardrails():
    """Demonstrate the safety guardrails system."""
    
    print("=" * 70)
    print("  PCLL SAFETY GUARDRAILS SYSTEM")
    print("=" * 70)
    print()
    
    # Section 1: Disclaimers
    print("SECTION 1: EXPLICIT DISCLAIMERS")
    print("-" * 70)
    print()
    
    for dtype, disclaimer in DISCLAIMERS.items():
        print(f"📋 {dtype.value.upper()}")
        print(f"   Title: {disclaimer.title}")
        print(f"   Must Acknowledge: {disclaimer.must_acknowledge}")
        print(f"   Show Frequency: {disclaimer.show_frequency}")
        print(f"   Preview: {disclaimer.text[:100]}...")
        print()
    
    # Section 2: Language Guardrails
    print()
    print("SECTION 2: LANGUAGE GUARDRAILS")
    print("-" * 70)
    print()
    
    guardrails = LanguageGuardrails()
    
    print("BLACKLISTED CATEGORIES:")
    print(f"  • Clinical terms: {len(guardrails.CLINICAL_BLACKLIST)} terms blocked")
    print(f"  • Wellness terms: {len(guardrails.WELLNESS_BLACKLIST)} terms blocked")
    print(f"  • Emotional terms: {len(guardrails.EMOTIONAL_BLACKLIST)} terms blocked")
    print(f"  • Motivational terms: {len(guardrails.MOTIVATIONAL_BLACKLIST)} terms blocked")
    print(f"  • Prescriptive patterns: {len(guardrails.PRESCRIPTIVE_PATTERNS)} patterns blocked")
    print()
    
    print("SAMPLE BLACKLISTED TERMS:")
    print(f"  Clinical: {', '.join(list(guardrails.CLINICAL_BLACKLIST)[:8])}...")
    print(f"  Wellness: {', '.join(list(guardrails.WELLNESS_BLACKLIST)[:8])}...")
    print(f"  Emotional: {', '.join(list(guardrails.EMOTIONAL_BLACKLIST)[:8])}...")
    print()
    
    # Section 3: Feature Limitations
    print()
    print("SECTION 3: FEATURE LIMITATIONS")
    print("-" * 70)
    print()
    
    categories = {}
    for limit in FEATURE_LIMITATIONS:
        if limit.category not in categories:
            categories[limit.category] = []
        categories[limit.category].append(limit)
    
    for category, limits in categories.items():
        print(f"📁 {category}")
        for limit in limits:
            print(f"   ❌ {limit.limitation}")
            print(f"      Rationale: {limit.rationale}")
        print()
    
    # Section 4: Risk Scenarios
    print()
    print("SECTION 4: RISK MITIGATION")
    print("-" * 70)
    print()
    
    for risk in RISK_SCENARIOS[:4]:  # Show first 4
        impact_emoji = "🔴" if risk.impact == "Critical" else "🟡" if risk.impact == "High" else "🟢"
        print(f"{impact_emoji} {risk.risk_id}: {risk.description}")
        print(f"   Likelihood: {risk.likelihood} | Impact: {risk.impact}")
        print(f"   Mitigations: {len(risk.mitigation_strategies)} strategies defined")
        print()
    
    # Section 5: Validation Demo
    print()
    print("SECTION 5: VALIDATION ENGINE DEMO")
    print("-" * 70)
    print()
    
    validator = SafetyValidator()
    
    test_cases = [
        # Should fail
        ("You seem stressed and overwhelmed today.", False),
        ("You should try to get more sleep.", False),
        ("Great job on your productivity!", False),
        ("This might indicate burnout symptoms.", False),
        
        # Should pass
        ("Today's withdrawals totaled 85 CU.", True),
        ("Balance closed at 45 CU.", True),
        ("Withdrawals exceeded deposits by 30 CU.", True),
        ("Decision-making accounted for 60% of costs.", True),
    ]
    
    print("Testing sample messages:")
    print()
    
    for text, expected_valid in test_cases:
        is_valid, violations = validator.validate_text(text)
        status = "✅ PASS" if is_valid else "❌ BLOCKED"
        expected = "✓" if is_valid == expected_valid else "✗ UNEXPECTED"
        
        print(f"  {status} [{expected}]: \"{text[:50]}{'...' if len(text) > 50 else ''}\"")
        if not is_valid:
            print(f"           Violations: {violations[0]}")
        print()
    
    # Section 6: Patent-Safe Terms
    print()
    print("SECTION 6: PATENT-SAFE TERMINOLOGY")
    print("-" * 70)
    print()
    
    terminology = PatentSafeTerminology()
    
    print("SAFE TERMS (public domain/established):")
    for term, explanation in list(terminology.SAFE_TERMS.items())[:6]:
        print(f"  ✓ {term}: {explanation}")
    print()
    
    print("POTENTIALLY PROBLEMATIC (avoid):")
    for term, concern in list(terminology.POTENTIALLY_PROBLEMATIC.items())[:4]:
        print(f"  ⚠️ {term}: {concern}")
    print()
    
    print("=" * 70)
    print("  Guardrails demonstration complete.")
    print("=" * 70)


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    demonstrate_guardrails()
    print()
    print("=" * 70)
    print("  COMPLIANCE CHECKLIST")
    print("=" * 70)
    print(generate_compliance_checklist())
